<?xml version="1.0"?>
<robot name="mbot" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <!-- PROPERTY LIST -->
    <xacro:property name="M_PI" value="3.1415926"/>
    <xacro:property name="base_mass"   value="20" /> 
    <xacro:property name="base_radius" value="0.20"/>
    <xacro:property name="base_length" value="0.16"/>

    <xacro:property name="wheel_mass"   value="10" />
    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_length" value="0.025"/>
    <xacro:property name="wheel_joint_y" value="0.19"/>
    <xacro:property name="wheel_joint_z" value="0.05"/>

    <xacro:property name="caster_mass"    value="0.5" /> 
    <xacro:property name="caster_radius"  value="0.06"/> <!-- wheel_radius - ( base_length/2 - wheel_joint_z) -->
    <xacro:property name="caster_joint_x" value="0.18"/>


    <!-- Defining the colors used in this robot -->
    <material name="silver">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>
    <material name="white">
        <color rgba="1 1 1 0.9"/>
    </material>
    <material name="blue">
        <color rgba="0 0 1 0.9"/>
    </material>
        <material name="black">
        <color rgba="0 0 0 0.95"/>
    </material>
    <material name="gray">
        <color rgba="0.5 0.5 0.5 0.95"/>
    </material>

    <!-- Macro for inertia matrix -->
    <xacro:macro name="sphere_inertial_matrix" params="m r">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0"
                iyy="${2*m*r*r/5}" iyz="0" 
                izz="${2*m*r*r/5}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                izz="${m*r*r/2}" /> 
        </inertial>
    </xacro:macro>


    <xacro:macro name="box_inertial_matrix" params="m l w h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(l*l+h*h)/12}" ixy = "0" ixz = "0"
                iyy="${m*(w*w+h*h)/12}" iyz = "0"
                izz="${m*(w*w+l*l)/12}" /> 
        </inertial>
    </xacro:macro>

    <!-- Macro for robot caster -->

    <xacro:macro name="R2D2_base">
    
     <link name="base_footprint">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.001 0.001 0.001" />
            </geometry>
        </visual>
      
    </link>
    
    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0 0 ${base_length/2 + caster_radius*2}" rpy="0 0 0" />        
            <parent link="base_footprint"/>
            <child link="base_link" />
    </joint>
    
    <link name="base_link">
        <visual>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="0.4" radius="0.20"/>
            </geometry>
            <material name="silver">
                <color rgba="0.75 0.75 0.75 1"/>
            </material>
        </visual>
         <collision>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="0.4" radius="0.28"/>
                </geometry>
            </collision>   
            <cylinder_inertial_matrix  m="5" r="0.2" h="0.4" />
    </link>

    <gazebo reference="base_link">
            <material>Gazebo/White</material>
    </gazebo>


    <joint name="left_arm_joint" type="fixed">
        <origin xyz="0 0.2 0.1" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="left_arm_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="left_arm_link">
        <visual>
            <origin xyz="0 0 -0.15" rpy="0 0 0" />
            <geometry>
                 <box size="0.05 0.01 0.3"/>
            </geometry>
            <material name="silver">
                <color rgba="0.75 0.75 0.75 1"/>
            </material>
        </visual>
        <collision>
            <origin  xyz="0 0 -0.15" rpy="0 0 0" />
            <geometry>
                <box size="0.05 0.01 0.3"/>
            </geometry>
         </collision>   
        <box_inertial_matrix  m="0.5" l="0.05" w="0.01" h="0.3" />     
    </link>

    <gazebo reference="left_arm_link">
            <material>Gazebo/White</material>
    </gazebo>
    
    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0 0 -0.3" rpy="0 0 0"/>
        <parent link="left_arm_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="left_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 0" />
            <geometry>
                <cylinder radius="0.06" length = "0.025"/>
            </geometry>
            <material name="white">
                <color rgba="1 1 1 0.9"/>
            </material>
        </visual>
         <collision>
            <origin xyz="0 0 0" rpy="1.5707 0 0" />
            <geometry>
                <cylinder radius="0.06" length = "0.025"/>
            </geometry>
        </collision>   
        <cylinder_inertial_matrix  m="${wheel_mass}" r="0.06" h="0.025" />
    </link>

    <joint name="right_arm_joint" type="fixed">
        <origin xyz="0 -0.2 0.1" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="right_arm_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="right_arm_link">
        <visual>
            <origin xyz="0 0 -0.15" rpy="0 0 0" />
            <geometry>
                 <box size="0.05 0.01 0.3"/>
            </geometry>
            <material name="silver">
                <color rgba="0.75 0.75 0.75 1"/>
            </material>
        </visual>
         <collision>
            <origin xyz="0 0 -0.15" rpy="0 0 0" />
            <geometry>
                <box size="0.05 0.01 0.3"/>
            </geometry>
        </collision>   
        <box_inertial_matrix  m="0.5" l="0.05" w="0.01" h="0.3" /> 
    </link>

    <gazebo reference="right_arm_link">
            <material>Gazebo/White</material>
    </gazebo>

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0 0 -0.3" rpy="0 0 0"/>
        <parent link="right_arm_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="right_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 0" />
            <geometry>
                <cylinder radius="0.06" length = "0.025"/>
            </geometry>
            <material name="white">
                <color rgba="1 1 1 0.9"/>
            </material>
        </visual>
         <collision>
            <origin xyz="0 0 0" rpy="1.5707 0 0" />
            <geometry>
                <cylinder radius="0.06" length = "0.025"/>
            </geometry>
        </collision>   
        <cylinder_inertial_matrix  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
    </link>

    <gazebo reference="right_wheel_link">
            <material>Gazebo/White</material>
    </gazebo>

    <joint name="front_block_joint" type="fixed">
        <origin xyz="0.2 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_block_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_block_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 1.5707" />
            <geometry>
                 <box size="0.05 0.01 0.1"/>
            </geometry>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 0.9"/>
            </material>
        </visual>      
    </link>

    <joint name="front_round1_joint" type="fixed">
        <origin xyz="0.0060001 0 0.025" rpy="0 0 0"/>
        <parent link="front_block_link"/>
        <child link="front_round1_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_round1_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 1.5707" />
            <geometry>
                <cylinder radius="0.02" length = "0.005"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 0.9"/>
            </material>
        </visual>

    </link>

    <gazebo reference="front_round1_link">
            <material>Gazebo/Black</material>
    </gazebo>

    <joint name="front_round2_joint" type="fixed">
        <origin xyz="0.0060001 0 -0.025" rpy="0 0 0"/>
        <parent link="front_block_link"/>
        <child link="front_round2_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_round2_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 1.5707" />
            <geometry>
                <cylinder radius="0.02" length = "0.005"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 0.9"/>
            </material>
        </visual>
    </link>

    <gazebo reference="front_round2_link">
            <material>Gazebo/Black</material>
    </gazebo>


    <joint name="front_brand1_joint" type="fixed">
        <origin xyz="0.055 0 0.15" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_brand1_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_brand1_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.15" length = "0.02"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 0.9"/>
            </material>
        </visual>
    </link>

    <gazebo reference="front_brand1_link">
            <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="front_brand2_joint" type="fixed">
        <origin xyz="0.055 0 0.12" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_brand2_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_brand2_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.15" length = "0.02"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 0.9"/>
            </material>
        </visual>
    </link>

    <gazebo reference="front_brand2_link">
            <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="front_brand3_joint" type="fixed">
        <origin xyz="0.055 0 0.09" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_brand3_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_brand3_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.15" length = "0.02"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 0.9"/>
            </material>
        </visual>
    </link>

    <gazebo reference="front_brand3_link">
            <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="neck_joint" type="continuous">
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="neck_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="neck_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.20001" length = "0.05"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 0.9"/>
            </material>
        </visual>
         <collision>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.20001" length = "0.05"/>
            </geometry>
        </collision>   
        <cylinder_inertial_matrix  m="${base_mass}" r="0.2" h="0.05" />
    </link>

    <gazebo reference="neck_link">
            <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="head_joint" type="continuous">
        <origin xyz="0 0 0.25" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="head_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="head_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="0.2" />
            </geometry>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 0.9"/>
            </material>
        </visual>
         <collision>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="0.2"/>
            </geometry>
        </collision>   
        <sphere_inertial_matrix  m="${base_mass}" r="0.2" />
    </link>

    <gazebo reference="head_link">
            <material>Gazebo/White</material>
    </gazebo>

    <joint name="front_caster_joint" type="continuous">
        <origin xyz="0.18 0 -0.2" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_caster_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_caster_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
            <material name="black">
                <color rgba="0 0 0 0.95"/>
            </material>
        </visual>
         <collision>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>   
        <sphere_inertial_matrix  m="${caster_mass}" r="${caster_radius}"  />
    </link>

    <gazebo reference="front_caster_link">
            <material>Gazebo/Black</material>
    </gazebo>

    <joint name="back_caster_joint" type="continuous">
        <origin xyz="-0.18 0 -0.2" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="back_caster_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="back_caster_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
            <material name="black">
                <color rgba="0 0 0 0.95"/>
            </material>
        </visual>
         <collision>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>   
        <sphere_inertial_matrix  m="${caster_mass}" r="${caster_radius}"  />
    </link>

    <gazebo reference="back_caster_link">
            <material>Gazebo/Black</material>
    </gazebo>

    <!-- controller -->
        <gazebo>
            <plugin name="differential_drive_controller" 
                    filename="libgazebo_ros_diff_drive.so">
                <rosDebugLevel>Debug</rosDebugLevel>
                <publishWheelTF>true</publishWheelTF>
                <robotNamespace>/</robotNamespace>
                <publishTf>1</publishTf>
                <publishWheelJointState>true</publishWheelJointState>
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <legacyMode>true</legacyMode>
                <leftJoint>left_wheel_joint</leftJoint>
                <rightJoint>right_wheel_joint</rightJoint>
                <wheelSeparation>${wheel_joint_y*2}</wheelSeparation>
                <wheelDiameter>${2*wheel_radius}</wheelDiameter>
                <broadcastTF>1</broadcastTF>
                <wheelTorque>30</wheelTorque>
                <wheelAcceleration>1.8</wheelAcceleration>
                <commandTopic>cmd_vel</commandTopic>
                <odometryFrame>odom</odometryFrame> 
                <odometryTopic>odom</odometryTopic> 
                <robotBaseFrame>base_footprint</robotBaseFrame>
            </plugin>
        </gazebo> 
    </xacro:macro>
</robot>
